  // // Add IDs to your tech stack options
  // export const techStackOptions = [
  //   { value: 'WebDevelopment', label: 'Web Development' },
  //   { value: 'MobileAppDevelopment', label: 'Mobile App Development' },
  //   { value: 'DataScience', label: 'Data Science' },
  //   { value: 'MachineLearning', label: 'Machine Learning' },
  //   { value: 'CloudComputing', label: 'Cloud Computing' },
  //   { value: 'Cybersecurity', label: 'Cybersecurity' },
  //   { value: 'DatabaseManagement', label: 'Database Management' },
  //   { value: 'DevOps', label: 'DevOps' },
  //   { value: 'FrontendDevelopment', label: 'Frontend Development' },
  //   { value: 'BackendDevelopment', label: 'Backend Development' },
  //   { value: 'UIUXDesign', label: 'UI/UX Design' },
  //   { value: 'ARVRDevelopment', label: 'AR/VR Development' },
  //   { value: 'Robotics', label: 'Robotics' },
  //   { value: 'GameDevelopment', label: 'Game Development' },
  //   { value: 'NetworkAdministration', label: 'Network Administration' },
  //   { value: 'SystemAdministration', label: 'System Administration' },
  //   { value: 'SoftwareTesting', label: 'Software Testing' },
  //   { value: 'ITConsulting', label: 'IT Consulting' },
  //   { value: 'E-commerce', label: 'E-commerce' },
  //   { value: 'HealthIT', label: 'Health IT' },
  //   { value: 'FinancialTechnology', label: 'Financial Technology (FinTech)' },
  //   { value: 'EducationalTechnology', label: 'Educational Technology (EdTech)' },
  //   { value: 'AIChatbots', label: 'AI Chatbots' },
  //   { value: 'CloudSecurity', label: 'Cloud Security' },
  //   { value: 'QuantumComputing', label: 'Quantum Computing' },
  //   { value: 'DataEngineering', label: 'Data Engineering' },
  //   { value: 'RemoteSensing', label: 'Remote Sensing' },
  //   { value: 'Virtualization', label: 'Virtualization' },
  //   { value: 'EmbeddedSystems', label: 'Embedded Systems' },
  //   { value: 'Bioinformatics', label: 'Bioinformatics' },
  //   { value: 'GeographicInformationSystems', label: 'Geographic Information Systems (GIS)' },
  //   { value: 'CloudStorage', label: 'Cloud Storage' },
  //   { value: 'WirelessCommunication', label: 'Wireless Communication' },
  //   { value: 'WebDesign', label: 'Web Design' },
  //   { value: 'DataAnalytics', label: 'Data Analytics' },
  //   { value: 'BusinessIntelligence', label: 'Business Intelligence' },
  //   { value: 'CRMSoftware', label: 'CRM Software' },
  //   { value: 'SupplyChainManagement', label: 'Supply Chain Management' },
  //   { value: 'Telecommunications', label: 'Telecommunications' },
  //   { value: 'SaaS', label: 'Software as a Service (SaaS)' },
  //   { value: 'PaaS', label: 'Platform as a Service (PaaS)' },
  //   { value: 'IaaS', label: 'Infrastructure as a Service (IaaS)' },
  //   { value: 'DataScience', label: 'Data Science' },
  //   { value: 'MachineLearning', label: 'Machine Learning' },
  //   { value: 'ArtificialIntelligence', label: 'Artificial Intelligence' },
  //   { value: 'CloudComputing', label: 'Cloud Computing' },
  //   { value: 'DatabaseManagement', label: 'Database Management' },
  //   { value: 'FullStackDevelopment', label: 'Full Stack Development' },
  //   { value: 'UIUXDesign', label: 'UI/UX Design' },
  //   { value: 'BigData', label: 'Big Data' },
  //   { value: 'Blockchain', label: 'Blockchain' },
  //   { value: 'IoT', label: 'Internet of Things (IoT)' },
  //   { value: 'ARVRDevelopment', label: 'AR/VR Development' },
  //   { value: 'Robotics', label: 'Robotics' },
  //   { value: 'GameDevelopment', label: 'Game Development' },
  //   { value: 'SystemAdministration', label: 'System Administration' },
  //   { value: 'SoftwareTesting', label: 'Software Testing' },
  //   { value: 'ITConsulting', label: 'IT Consulting' },
  //   { value: 'E-commerce', label: 'E-commerce' },
  //   { value: 'HealthIT', label: 'Health IT' },
  //   { value: 'FinancialTechnology', label: 'Financial Technology (FinTech)' },
  //   { value: 'EducationalTechnology', label: 'Educational Technology (EdTech)' },
  //   { value: 'AIChatbots', label: 'AI Chatbots' },
  //   { value: 'CloudSecurity', label: 'Cloud Security' },
  //   { value: 'QuantumComputing', label: 'Quantum Computing' },
  //   { value: 'DataEngineering', label: 'Data Engineering' },
  //   { value: 'SQL', label: 'SQL' }, 
  //   { value: 'NoSQL', label: 'NoSQL' },
  //   { value: 'PLSQL', label: 'PLSQL' }, 
  //   { value: 'Python', label: 'Python' },
  //   { value: 'Java', label: 'Java' },
  //   { value: 'C++', label: 'C++' },
  //   { value: 'C PROGRAMING', label: 'C PROGRAMING' },
  //   { value: 'Ruby', label: 'Ruby' },
  //   { value: 'Swift', label: 'Swift' },
  //   { value: 'JavaScript', label: 'JavaScript' },
  //   { value: 'ReactJS', label: 'ReactJS' },
  //   { value: 'React Native', label: 'React Native' },
  //   { value: 'AngularJS', label: 'AngularJS' },
  //   { value: 'Angular', label: 'Angular' },
  //   { value: 'VueJS', label: 'VueJS' },
  //   { value: 'Node.js', label: 'Node.js' },
  //   { value: 'Django', label: 'Django' },
  //   { value: 'ASP.NET', label: 'ASP.NET' },
  //   { value: 'Power BI', label: 'Power BI' },
  //   { value: 'SAP HANA', label: 'SAP HANA' },
  //   { value: 'SAP FI with S/4 HANA', label: 'SAP FI with S/4 HANA' },
  //   { value: 'SAP ABAP', label: 'SAP ABAP' },
  //   { value: 'Mulesoft Developer', label: 'Mulesoft Developer' },
  //   { value: 'MS Dynamics 365', label: 'MS Dynamics 365' },
  //   { value: 'Java Microservices', label: 'Java Microservices' },
  //   { value: 'C#', label: 'C#' },
  //   { value: 'AWS', label: 'AWS' },
  //   { value: 'Azure', label: 'Azure' },  
  //   { value: 'Terraform', label: 'Terraform' },  
  //   { value: 'Ansible', label: 'Ansible' },  
  //   { value: 'MySQL', label: 'MySQL' },  
  //   { value: 'SQL Server', label: 'SQL Server' },  
  //   { value: 'Jenkins', label: 'Jenkins' },  
  //   { value: 'PHP', label: 'PHP' },  
  //   { value: 'Golang', label: 'Golang' },  
  //   { value: 'MVC', label: 'MVC' },  
  //   { value: 'WEBAPI', label: 'WEBAPI' },  
  //   { value: 'Dell Boomi', label: 'Dell Boomi' },  
  //   { value: 'DotNet Core', label: 'DotNet Core' },  
  //   { value: '.Net Core', label: '.Net Core' },  
  //   { value: 'Selenium', label: 'Selenium' },  
  //   { value: 'JMeter', label: 'JMeter' },  
  //   { value: 'K6', label: 'K6' },  
  //   { value: 'Pyspark', label: 'Pyspark' },  
  //   { value: 'Scala', label: 'Scala' },  
  //   { value: 'Informatica', label: 'Informatica' },  
  //   { value: 'Hive', label: 'Hive' },  
  //   { value: 'Snowflake', label: 'Snowflake' },  
  //   { value: 'Airflow', label: 'Airflow' },  
  //   { value: 'Databricks', label: 'Databricks' },  
  //   { value: 'Tableau', label: 'Tableau' },  
  //   { value: 'GCP', label: 'GCP' },  
  //   { value: 'Springboot', label: 'Springboot' },  
  //   { value: 'Cloud Developer', label: 'Cloud Developer' },  
  //   { value: 'ETL Developer', label: 'ETL Developer' },  
  //   { value: 'ETL Tester', label: 'ETL Tester'}, 
  //   { value: 'Hadoop', label: 'Hadoop'}, 
  //   { value: 'SSIS', label: 'SSIS'}, 
  //   { value: 'SSRS', label: 'SSRS'}, 
  //   { value: 'Kafka', label: 'Kafka'}, 
  //   { value: 'Excel', label: 'Excel'}, 
  //   { value: 'BigQuery', label: 'BigQuery'}, 
  //   { value: 'PostgreSQL', label: 'PostgreSQL'}, 
  //   { value: 'Project Manager', label: 'Project Manager'}, 
  //   { value: 'Sr Project Manager', label: 'Sr Project Manager'}, 
  //   { value: 'Project Coordinator', label: 'Project Coordinator'}, 
  //   { value: 'Scrum Master', label: 'Scrum Master'}, 
  //   { value: 'Sales', label: 'Sales'}, 
  //   { value: 'Sales Manager', label: 'Sales Manager'}, 
  //   { value: 'Digital Marketing ', label: 'Digital Marketing '}, 
  //   { value: 'Technical Writer', label: 'Technical Writer'}, 
  //   { value: 'Content Writer ', label: 'Content Writer '}, 
  //   { value: 'ServiceNow Developer', label: 'ServiceNow Developer'}, 
  //   { value: 'ServiceNow Admin', label: 'ServiceNow Admin'}, 
  //   { value: 'Odoo Developer', label: 'Odoo Developer'},  
  //   { value: 'Next.js', label: 'Next.js'},  
  //   { value: 'Express.js', label: 'Express.js'},  
  //   { value: 'MongoDB', label: 'MongoDB'},  
  //   { value: 'LoadRunner', label: 'LoadRunner'},  
  //   { value: 'Kubernetes', label: 'Kubernetes'},  
  //   { value: 'Docker', label: 'Docker'},  
  //   { value: 'Prometheus', label: 'Prometheus'},  
  //   { value: 'Grafana', label: 'Grafana'},  
  //   { value: 'Bitbucket', label: 'Bitbucket'},  
  //   { value: 'GitHub Actions', label: 'GitHub Actions'},  
  //   { value: 'Data Migration', label: 'Data Migration'},  
  //   { value: 'Microsoft Synapse', label: 'Microsoft Synapse'},  
  //   { value: 'Azure Datafactory', label: 'Azure Datafactory'},  
  //   { value: 'Azure DataLake ', label: 'Azure DataLake '},  
  //   { value: 'Azure Databricks', label: 'Azure Databricks'},  
  //   { value: 'Azure Blob Storage', label: 'Azure Blob Storage'},  
  //   { value: 'DBA', label: 'DBA'},  
  //   { value: 'Oralce DBA ', label: 'Oralce DBA'},  
  //   { value: 'Magento', label: 'Magento'},  
  //   { value: 'Application Support Engineer', label: 'Application Support Engineer'},  
  //   { value: 'WordPress', label: 'WordPress'},  
  //   { value: 'PowerShell', label: 'PowerShell'},  
  //   { value: 'JIRA', label: 'JIRA'},  
  //   { value: 'Flutter', label: 'Flutter'},  
  //   { value: 'Android Studio', label: 'Android Studio'},  
  //   { value: 'Kotlin', label: 'Kotlin'},  
  //   { value: 'MVVM', label: 'MVVM'},  
  //   { value: 'DART', label: 'DART'},  
  //   { value: 'Fresher', label: 'Fresher'},
  //   { value: 'QA Automation', label: 'QA Automation'},
  //   { value: 'DotNet Developer', label: 'DotNet Developer'},
  //   { value: 'TA', label: 'TA'},
  //   { value: 'Data Brick', label: 'Data Brick'},
  //   { value: 'SAP FICO', label: 'SAP FICO'},
  //   { value: 'MBA Internship', label: 'MBA Internship'},
  //   { value: 'Senior Developer - MS Dynamics 365', label: 'Senior Developer - MS Dynamics 365'},  
  //   { value: 'Pega Admin', label: 'Pega Admin'},  
  //   { value: 'Software QA Enginer', label: 'Software QA Enginer'},  
  //   { value: 'Intern', label: 'Intern'},
  //   { value: 'Azure Integration Lead', label: 'Azure Integration Lead'},
  //   { value: 'Network Engineer', label: 'Network Engineer'},
  //   { value: 'QA with Manual Testing', label: 'QA with Manual Testing'},
  //   { value: 'Anaplan Modeller', label: 'Anaplan Modeller'},
  //   { value: 'SAP Native HANA', label: 'SAP Native HANA'},
  //   { value: 'SAP PS', label: 'SAP PS'},
  //   { value: 'SAP Basis', label: 'SAP Basis'},
  //   { value: 'Sales Excuetive', label: 'Sales Excuetive'},
  //   { value: 'Talent Acquisition', label: 'Talent Acquisition'},
  //   { value: 'Pricing Engineer', label: 'Pricing Engineer'},
  //   { value: 'Bench Resource', label: 'Bench Resource'},
  //   ];

    export const jobModeOptions = [
    { value: 'FTE', label: 'FTE' },
    { value: 'Contract', label: 'Contract' },
    { value: 'C2H', label: 'C2H' },
  ];

  export const modeOptions = [
    { value: 'Work from Home', label: 'Work from Home' },
    { value:  'Work from Office', label: 'Work from Office' },
    { value: 'Hybrid', label: 'Hybrid' },
  ];

  export const indianStateswithmetropolitanCities = [
    { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
    { value: 'Ladakh', label: 'Ladakh' },
    { value: 'Arunachal Pradesh', label: 'Arunachal Pradesh' },
    { value: 'Assam', label: 'Assam' },
    { value: 'Bihar', label: 'Bihar' },
    { value: 'Chhattisgarh', label: 'Chhattisgarh' },
    { value: 'Goa', label: 'Goa' },
    { value: 'Gujarat', label: 'Gujarat' },
    { value: 'Haryana', label: 'Haryana' },
    { value: 'Himachal Pradesh', label: 'Himachal Pradesh' },
    { value: 'Jharkhand', label: 'Jharkhand' },
    { value: 'Karnataka', label: 'Karnataka' },
    { value: 'Kerala', label: 'Kerala' },
    { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
    { value: 'Maharashtra', label: 'Maharashtra' },
    { value: 'Manipur', label: 'Manipur' },
    { value: 'Meghalaya', label: 'Meghalaya' },
    { value: 'Mizoram', label: 'Mizoram' },
    { value: 'Nagaland', label: 'Nagaland' },
    { value: 'Odisha', label: 'Odisha' },
    { value: 'Punjab', label: 'Punjab' },
    { value: 'Rajasthan', label: 'Rajasthan' },
    { value: 'Sikkim', label: 'Sikkim' },
    { value: 'Tamil Nadu', label: 'Tamil Nadu' },
    { value: 'Telangana', label: 'Telangana' },
    { value: 'Tripura', label: 'Tripura' },
    { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
    { value: 'Uttarakhand', label: 'Uttarakhand' },
    { value: 'West Bengal', label: 'West Bengal' },
    { value: 'Andaman and Nicobar Islands', label: 'Andaman and Nicobar Islands' },
    { value: 'Chandigarh', label: 'Chandigarh' },
    { value: 'Dadra and Nagar Haveli and Daman and Diu', label: 'Dadra and Nagar Haveli and Daman and Diu' },
    { value: 'Lakshadweep', label: 'Lakshadweep' },
    { value: 'Puducherry', label: 'Puducherry' },
    { value: 'Bengaluru', label: 'Bengaluru' },
    { value: 'Chennai', label: 'Chennai' },
    { value: 'Hyderabad', label: 'Hyderabad' },
    { value: 'Kolkata', label: 'Kolkata' },
    { value: 'Pune', label: 'Pune' },
    { value: 'Ahmedabad', label: 'Ahmedabad' },
    { value: 'Surat', label: 'Surat' },
    { value: 'Jaipur', label: 'Jaipur' },
    { value: 'Lucknow', label: 'Lucknow' },
    { value: 'Kanpur', label: 'Kanpur' },
    { value: 'Nagpur', label: 'Nagpur' },
    { value: 'Patna', label: 'Patna' },
    { value: 'Indore', label: 'Indore' },
    { value: 'Thane', label: 'Thane' },
    { value: 'Bhopal', label: 'Bhopal' },
    { value: 'Visakhapatnam', label: 'Visakhapatnam' },
    { value: 'Vadodara', label: 'Vadodara' },
    { value: 'Firozabad', label: 'Firozabad' },
    { value: 'Ludhiana', label: 'Ludhiana' },
    { value: 'Rajkot', label: 'Rajkot' },
    { value: 'Agra', label: 'Agra' },
    { value: 'Siliguri', label: 'Siliguri' },
    { value: 'Nashik', label: 'Nashik' },
    { value: 'Faridabad', label: 'Faridabad' },
    { value: 'Patiala', label: 'Patiala' },
    { value: 'Meerut', label: 'Meerut' },
    { value: 'Kalyan-Dombivli', label: 'Kalyan-Dombivli' },
    { value: 'Vasai-Virar', label: 'Vasai-Virar' },
    { value: 'Varanasi', label: 'Varanasi' },
    { value: 'Srinagar', label: 'Srinagar' },
    { value: 'Dhanbad', label: 'Dhanbad' },
    { value: 'Jodhpur', label: 'Jodhpur' },
    { value: 'Amritsar', label: 'Amritsar' },
    { value: 'Raipur', label: 'Raipur' },
    { value: 'Allahabad', label: 'Allahabad' },
    { value: 'Coimbatore', label: 'Coimbatore' },
    { value: 'Jabalpur', label: 'Jabalpur' },
    { value: 'Gwalior', label: 'Gwalior' },
    { value: 'Vijayawada', label: 'Vijayawada' },
    { value: 'Madurai', label: 'Madurai' },
    { value: 'Guwahati', label: 'Guwahati' },
    { value: 'Hubli-Dharwad', label: 'Hubli-Dharwad' },
    { value: 'Mysuru', label: 'Mysuru' },
    { value: 'Tirunelveli', label: 'Tirunelveli' },
    { value: 'Bareilly', label: 'Bareilly' },
    { value: 'Bhavnagar', label: 'Bhavnagar' },
    { value: 'Bikaner', label: 'Bikaner' },
    { value: 'Bokaro Steel City', label: 'Bokaro Steel City' },
    { value: 'Bangalore', label: 'Bangalore' },
    { value: 'Amaravati', label: 'Amaravati' }, 
    { value: 'Itanagar', label: 'Itanagar' }, 
    { value: 'Dispur', label: 'Dispur' },
    { value: 'Patna', label: 'Patna' }, 
    { value: 'Raipur', label: 'Raipur' }, 
    { value: 'Panaji', label: 'Panaji' }, 
    { value: 'Gandhinagar', label: 'Gandhinagar' }, 
    { value: 'Shimla', label: 'Shimla' }, 
    { value: 'Ranchi', label: 'Ranchi' },
    { value: 'Thiruvananthapuram', label: 'Thiruvananthapuram' }, 
    { value: 'Bhopal', label: 'Bhopal' }, 
    { value: 'Mumbai', label: 'Mumbai' }, 
    { value: 'Imphal', label: 'Imphal' },
    { value: 'Shillong', label: 'Shillong' }, 
    { value: 'Aizawl', label: 'Aizawl' }, 
    { value: 'Kohima', label: 'Kohima' }, 
    { value: 'Bhubaneswar', label: 'Bhubaneswar' }, 
    { value: 'Jaipur', label: 'Jaipur' }, 
    { value: 'Gangtok', label: 'Gangtok' },  
    { value: 'Agartala', label: 'Agartala' }, 
    { value: 'Lucknow', label: 'Lucknow' },
    { value: 'Dehradun', label: 'Dehradun' }, 
    { value: 'Kolkata', label: 'Kolkata' }, 
    { value: 'Port Blair', label: 'Port Blair'}, 
    { value: 'Delhi', label: 'Delhi' },
    { value: 'Noida', label: 'Noida' },
    { value: 'Aurangabad', label: 'Aurangabad'},
    { value: 'Tirupati', label: 'Tirupati'},
    { value: 'Villiupuram', label: 'Villiupuram'},
    { value: 'Nellore', label: 'Nellore'},
    { value: 'Chattisgarh', label: 'Chattisgarh'},
    { value: 'Trichy', label: 'Trichy'},
    { value: 'Gurgaon ', label: 'Gurgaon '},
    { value: 'Chengelpet ', label: 'Chengelpet '},
    { value: 'Pudukottai ', label: 'Pudukottai '},
    { value: 'Rohtak ', label: 'Rohtak '},
    { value: 'Pondycherry ', label: 'Pondycherry '},
    
];


export const customStyles = {
  control: (provided, state) => ({
    ...provided,
    width: '100%', // Adjust the width as needed
    borderColor: state.isFocused ? 'rgb(145, 125, 145)' : 'rgb(128, 128, 128)', // Yellow border color on focus, gray when not focused
  }),
  option: (provided, state) => ({
    ...provided,
    backgroundColor: state.isFocused ? 'rgb(142, 147, 230)' : 'white', // Light blue background color on hover/focus, white when not focused
    color: state.isFocused ? 'rgb(896, 596, 255)' : 'black', // Blue text color on hover/focus, black when not focused
  }),
  // Add more custom styles as needed
};